### ISSUE TITLE
Game Mechanic Issue: Attack Que and Move Que

### ISSUE THREAD

**Issue by TommyZynos** [jiminssy/ZhynosAdventure#4]
Let's implement attack cues as well.
Currently it's only for Movement.
Also, there's a weird delay when you click on tiles to move.

**Comment by jiminssy** [comment]
Any action in the game is queued right now.
Here are the action types:
- move
- normal attack
- any skills activated
Game will only remember **one** action you queue regardless of the action type.

The delay you are seeing after moving is because the character is resting.
If you move many tiles you have to rest longer.
If you normal attack, you rest short time.
If you do powerful skill, you have to rest longer time even though you haven't moved.

This is because this game requires you to manage your resources in the form of "time", not like traditional "mana" driven play. Time is the most valuable resource in this game and you have to use it well otherwise you can get killed while you are "resting" if you are making the wrong move. Every move counts.

Character's Agility attribute affects how much you "rest". If you are assassin and wearing lots of agility gears, your agility will be high. So it will globally reduce the amount of time you have to rest after any action. You can move around like crazy and killing people fast while other slower classes are taking rests.
